### ISSUE TITLE
The tac scanner screen dissapears immedately if you don't press the fire button.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#202] opened 2022-07-10 20:44 UTC
0.85 PE in demo mode

Play level 13 in demo mode and complete it. When the tac scan screen shows up don't press the fire button. The screen will appear and almost immediately exit and you'll be playing the space battle.

**Comment by jessaskey** [comment] 2022-07-14 23:07
So it should be so that the approaching station needs to at least zoom all the way down onto the screen center and the range should be at 32... if you don't hit the breakout start button before then (and in the case of level 14, there is no message about the warps), the tactical scanner will zoom in and end fairly quick... you really do have to hit the button to launch the ball pretty quickly.

**Comment by bakerhillpins** [comment] 2022-07-16 01:32
This has been a point of confusion and frustration for me during game play. I'll take a video when I get back to the house. I don't feel that the timeouts give time to read the message at the top and interact with the warps/breakout. So for me it's takes away from the experience.  I'll say that this was an issue with the OEM game too. I'm not sure if you've modified the code in this area but it does feel much worse than OEM.

How does the game keep track of time? Is it just counting main execution loops? Info I've found online says that accurate time on a 6502 requires external logic.  I know we removed that window code and wonder if other changes have caused the timing to change.

**Comment by jessaskey** [comment] 2022-07-16 16:03
So, the timing code in the main game is structured a little funny and I could certainly restructure it, but I fear at this late point that I may intro bugs... but here are my thoughts as I think you are pretty on point with your feedback too..

Overall, the tactical scanner timer is based upon a counter of 'ticks' (which is 16 frame counts = about 1/2 second)... the original code has a main timer of 12 ticks (about 5 seconds).... this is the end of the tact scan if the ball is not launched. Once the ball is launched, then the tact scan will always​ be 30 ticks (about 13 seconds).... so you really have to launch the ball as soon as possible because even that time that you don't launch the ball, is counting towards your total time... for max breakout time, launch instantly. This exposes one of the other annoyances with the game I think and that is if you end up missing the breakout ball then the tact scan sits there for those remaining 13 seconds and you wait and wait (it seems forever).

I guess that if I were to change it, then I would propose something like this...

If ball not launched, give it up to maybe 8 seconds to launch the ball (3 more seconds). This will give time to read things if you want. Main timer would stay at 13 seconds but the one thing I could try and do is something along the lines of if you miss the ball (or multiple balls if on second pass of breakout), then let the sound finish and then instantly end the scanner because there is nothing left to do.

thoughts?
________________________________

**Comment by bakerhillpins** [comment] 2022-07-18 13:17
> the original code has a main timer of 12 ticks (about 5 seconds).... this is the end of the tact scan if the ball is not launched. Once the ball is launched, then the tact scan will always​ be 30 ticks (about 13 seconds).... so you really have to launch the ball as soon as possible because even that time that you don't launch the ball, is counting towards your total time... 

This is the confusion for me, If the no button press delay were 5 seconds I don't think I'd be upset but it absolutely doesn't feel like 5 seconds.  Honestly, It seems random. I'm going to go downstairs and grab some video and that will provide actual time. Maybe I'm crazy..

Also, I wonder if our removal of the 'waste' vector has changed the timing enough to make it shorter? (actual time shorter)

Yea, I'd like to see this be a bit more user friendly..  Mostly it's the initial delay that kills it for me, Maybe if it triggers off of ANY user input, so that moving the controller makes it wait too. This keeps the frantically trying to pick the first digit of the warp to a minimum and allows you time to read.  I guess we're battling 2 issues.. waiting long enough for someone to do something (for those that know what to do) and not too long for someone who's really just sitting there with no clue.

**Comment by bakerhillpins** [comment] 2022-07-18 15:48
2 videos for you. 1st is starting at level 13.. there's 5 seconds between landing on the tac scan page and when the ball launches. BTW - I didn't press any button it just launches by itself.  Then the 2nd is after finishing level 13, it's maybe 2-3 seconds and goes away...  Obviously watch the time on the video to see what I'm talking about.



https://user-images.githubusercontent.com/5980709/179553811-b31118e2-eadf-4d4e-8f75-fe82c63edfd7.mp4


https://user-images.githubusercontent.com/5980709/179553825-5463a421-250b-4e49-addd-c5ba48f4d676.mp4

**Comment by bakerhillpins** [comment] 2022-07-18 16:35
Got the instant exit. I had just played the 2nd XX level, and decided to start at level 1. And it instant exits. Not sure if this is a demo mode problem though.

https://user-images.githubusercontent.com/5980709/179559655-80c19d60-7fdc-4c4b-9976-756bd509bfd7.mp4

**Comment by jessaskey** [comment] 2022-07-19 00:38
Okay, I found that bug that was 'auto launching' the ball and that issue is fixed. It was only happening on levels where the warp message was being displayed.

On that second video... that is pretty much by design the way it works... once the ship zooms into range and ends at range 32 (and as long as there is not a warp message being displayed)... then the Tactical Scanner is OVER!  You gotta hit your button before range gets to 32. :-)

**Comment by jessaskey** [comment] 2022-07-19 00:39
The one thing I see in your video tho that is a little disturbing is that the ship and your score are dissappearing upon the ship zooming in from the maze end and into the tact scan. That might be a bug, Im going to try and fix that under this issue too.

**Comment by bakerhillpins** [comment] 2022-07-19 00:43
> On that second video... that is pretty much by design the way it works... once the ship zooms into range and ends at range 32 (and as long as there is not a warp message being displayed)... then the Tactical Scanner is OVER! You gotta hit your button before range gets to 32. :-)

Look at the time on the video.. you're in the tac scanner for a tad over 3 seconds where you're saying above it should be 5 so that's really what I'm driving at here.

**Comment by jessaskey** [comment] 2022-07-19 00:48
Well, when I say '5'.... you gotta take that lose because I typically talk about the units/tics used in code, plus when I count manually, Im probably not being very accurate.

**Comment by jessaskey** [comment] 2022-07-19 00:54
and... a follow up note on the ship and score disappearing... it is not happening on MAME so it could be either a bug or an inadvertent spot killer on your monitor causing this?  Either way, Im going to put this in a a separate bug and then we can close this one!

**Comment by bakerhillpins** [comment] 2022-07-19 00:56
What about the instant exit during Demo Mode Play... The 3rd video?

**Comment by jessaskey** [comment] 2022-07-19 13:55
Okay, I see it now, sorry... looking at it now! :-)

**Comment by jessaskey** [comment] 2022-07-19 14:12
So the one thing that *can* happen right there when your tact exits is that this is the point in the code where it looks to see if you have a tesseract in your pocket and if so, the wormhole animation starts right at 3 ticks (1.5 seconds approx)... so Im suspecting that this is a bug around the tesser variables. I just did this process on MAME and was not able to trigger this bug tho, so Im having a hard time duplicating it....  Played 2nd level XX, got all the way into the maze before dying completely... started a new game and played on level 1.

**Comment by jessaskey** [comment] 2022-07-19 14:28
and... one more comment on this... after digging around, You must have played something previously that left one of the tesser variables set in a funky way. I looked around and noticed that for some reason I wasn't clearing these variables at the start of the game. So... I added all the token vars and reset them at game start now... Im hoping that this should fix it just because I am not able to reproduce in practice, just theory.

**Comment by bakerhillpins** [comment] 2022-07-19 19:39
Testing on 0.86 PE..  (will edit this as I test each of the issues in here)

Level 13 - Tac Scan ball auto launches (fixed)
Instant Exit Tac Scan on level 1 after 2nd XX level (fixed)
Score and Ship (blank screen) after Level 13 (fixed)

**Closed as completed** 2022-08-30 01:20 UTC
Labels: bug
