### ISSUE TITLE
The upper 1/4 of the screen flashes randomly during the Catastrofigher landing animation.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#170] opened 2022-04-03 12:55 UTC
The scores/lives that's in the upper 1/4 of the screen is dropping a few "frames" during this animation. I recorded a slo-mo video to show the weirdness.

https://drive.google.com/file/d/10QUrQkmh6wN-O7c_Q_vcHa4HtAjnx0uG/view?usp=sharing

It also appears like this might be going on during the attract mode as the upper part of the M and H in the Major Havoc text seems to drop out at odd intervals.

Overall, there's a lot feeling of "dropped" frames during play too. It's noticeable but the interval is not consistent. I've seen the Catastrofighter flash up on the screen during attract mode too which is where it doesn't belong.  If you listen to the monitor you can hear it skip a beat during the drawing, and occasionally it sounds like it's "straining" - not sure how to describe it but it's one of those sounds that make you think the game just went all wonky.  

Thinking about all this over the past 2 days it's like the vector generator state machine goes off in the weeds and watchdogs and then starts back up again. It would explain a lot of the stuff that's going on.

I should probably check this out again now that https://github.com/jessaskey/mhavocpe/issues/167 is fixed since bad initialization could easily cause this down stream.

**Comment by jessaskey** [comment] 2022-04-03 15:33
#167 might have done something, but Im not sure it will solve this. I also found that the Y Window was being set in some code around the drawing of the scores and I cleared it for this next build. We will have to see what happens like you mentioned.

**Comment by jessaskey** [comment] 2022-04-16 16:20
Okay, Im not sure that this is actually a Y-Window situation after all. I think the issue is deeper because as far as I can tell, the Y-Window is working correctly now that @bakerhillpins and I went through and discussed how the Y Sample and Hold circuit works to actually make the Y-Window effect. The biggest issue I have found is that the MAME VGenerator is obviously different in how it executes vectors and also has MASSIVELY better performance than the VG hardware on the PCB, so MAME masks a lot of issues that only show on physical hardware (this bug appears to be one of them).

**Comment by jessaskey** [comment] 2022-04-16 16:22
Note that this is still a BUG and I have confirmed that on my current 0.79 ROMs that it flickers badly on physical hardware but works fine in MAME. It does appear that the flickering only happens during the TW_SHIP library for rendering the ship on the screen because the flickering happens anytime the ship is on the screen EXCLUDING the time in the maze. Notable is that the ship rendering during the maze (ship sitting on top) is done via a different routine, so that should help determine when this is happening. Need to investigate more.

**Comment by jessaskey** [comment] 2022-04-16 17:04
A general big braindump on some of the nuances of the Vector Generator and Alpha Processor interactions...

**6502 Loop vs VG Loop**

Major Havoc has a double-buffered Vector Generator memory structure. The overall idea is that the 6502 Alpha processor fills one VGRAM buffer (located at $4002) and then when it is done, it sends the VGGO signal to the VG to start processing. As soon as it send the VGGO, it starts filling up the other VGRAM buffer (located at $4800)…. And again, when it is done filling that buffer, it will send the VGGO signal again to have it start executing the second buffer while the Alpha CPU goes back to filling the first buffer again. The actual mechanism for flipping the buffers is done by changing the FIRST instruction at $4000 (which is simply a JUMP instruction)…. The code just XOR’s the JUMP TO address with a $0002 bit and toggles it each time. That is the easiest way to have the VG jump to each buffer start.

The above cycle is pretty simple and there are some things that can happen that might disrupt that assumed behavior above…

1. The VG might not be done rendering the Vector RAM buffer by the time the Alpha CPU comes back to flip to the other vector buffer.

* The Alpha CPU monitors this situation by counting the number of IRQ’s that have passed since the VG started and until the VG signals it is completed with the current buffer by asserting the VGHALT signal which the Alpha CPU looks at each loop.

    * If the IRQ count exceeds 20d, then the Alpha CPU assumes that the VG has crashed for whatever reason and does a VGRESET.
        * Questions still to answer
            * Im currently monitoring this situation and considering trying to track down all the situations in the code where this happens (is probably a bug from the original game, that this process ‘fixes’. I would prefer to take this code out and just fix all the situations where this might happen, but in the end, it probably needs to stay in for release ‘just in case’… because with this code, the screen simply drops for single frame, but without this code, the game will reset back to attract mode (watchdog reset).
            * Does the VG come back from this situation in the opposite buffer? Assume yes, but need to verify.
2.	The VG might finish drawing the current buffer BEFORE the Alpha CPU is done filling the next buffer.
    * The Alpha knows that in some situations this will happen (well actually only one)  and that is when the Alpha is loading up a new maze definition upon touchdown of the ship on the landing pad. Because Owen knows this process took a long time, they set a VGRESTART memory flag. So in this situation, when the VG is done and VGRESTART is set, then the IRQ loop will simply start the VG again to draw the same picture (you can sort of see this happen on landing when the screen keeps rendering but sorta ‘freezes’).
        * Questions
            * Does this restart jump to the other buffer as well? Seems like it should not…. Since this is done in the IRQ and the base pointer switch happens in the main loop, are we sure that this doesn’t ever accidentally restart the VG on the other incomplete buffer? The way to check this would be that the Alpha CPU would not actually switch the base pointer until AFTER it is done rendering the VGRAM instructions in the next buffer.
            * Are there any other situations in code where this happens outside of the landing sequence… right now I know that the VGRESTART is only ever set for that specific situation… but if the VG finishes early in other situations, it may make sense to do this in those places as well because otherwise, the VG will sit idle and the screen will simply GO BLACK (this is a potential reason for the whole screen flickering/dropping).  The downside of doing this is that if the buffer is large and we restart the VG, we will put ourselves into a race situation where the VG is not finished, so we start it again, but then we fall into the main scenario 1 above where the Alpha CPU is then waiting for the vg TO finish again.
    * When the VGRESTART is NOT set and this happens, the Alpha code does something Im not entirely sure about why…. The VGRAM jump pointer sitting at $4000 is OVERWRITTEN with straight up code that JSRS to a routine in VROM that draws a black box around the border of the screen and then does a VGHALT. The Alpha writes this code…. jsr waste, vghalt. Then starts the vector generator, waits with 8 NOP instructions, then puts the VGPOINTER back to what it was (JMP to correct buffer).
        * I have no idea why it does this… maybe just to keep the deflection moving instead of settling down? 
        * It should be noted that this prevents any type of RACE condition as above because it is a very short vector sequence, so it isn’t like this will make the main loop above see the VG as not halted.
        * I may experiment with removing this but it won’t gain us anything… Im going to ask Owen about this.

**Current BUG:** Reasons why the screen may be flickering – seems to be only when the tw_ship routine is being called to draw ship on screen (not during Maze however with Ship sitting on maze, that is a different ship routine)

1. ~~The VG is trying to draw crap vectors, crashes and is reset by the Alpha after not completing~~
    * In MAME this does not happen because I don’t get to VG resets during the ‘flickering parts’
    * ~~On real hardware, this would be the case if the VGRESET is pulsing during  any of the scenes that have the flickering issue~~
    * I have verified on physical hardware that the VGRESET does *not* pulse when the flickering occurs
2. The VG is drawing crap vectors, but still VGHALTS appropriately so the only effect as that the screen ‘drops to black’ while the VG is apparently drawing said crap.
    * I actually don’t think this is the case because most drawn ‘crap’ should be visible with at least something on screen, so we should be seeing flashes of crap in this case, and it doesn’t appear that we are seeing anything like that.
3. The VG is not being told to draw anything, it is finished and waiting.
    * I think that in this case, I can find this in MAME and the results should apply to the physical hardware too because this should show itself by running the ‘waste’ vectors.
    * I can also make the ‘waste’ vectors visible as a RED box instead of a BLACK box and this will become apparent on physical ROM’s… the change is a single bit on the 64K VROM.

**Comment by jessaskey** [comment] 2022-04-30 18:00
I ended up going down the Waste vector as a RED (visible) box for testing on this... and while Im not entirely sure why at this point, the 'waste' vector is what is causing the flicker on the physical hardware. By making it visible, it is clear that during each flicker, the VG is trying to draw the red box. Oddly tho, on my machine, the actual drawing of the box is sorta 'glitching' out and doing something that ends up affecting the other vectors and causing the 'flicker'... more to come.

**Comment by bakerhillpins** [comment] 2022-05-01 14:14
The flickering seems to be corrected.

This new build is looking really good. I need to spend some more time playing but it's really smooth. Haven't seen any flicker yet. Trying to play some of the upper levels.

**Comment by jessaskey** [comment] 2022-05-01 17:37
I'm going to close this specific issue as well to wrap up the v0.79 release (next release I send will be in the v0.80 milestone). It does still seem like there are some 'speed' timing issues that we need to resolve, but I would prefer to solve those separately now. Until the value of the 'waste' process becomes apparent, Im going to take it out as it generally slows down the game overall... Im a little worried that since we are testing this on MAME and physical games with the Amplifones, that at some point someone with a WG6100 conversion (tempest/SD/Gravitar) will leave some feedback saying that their spot killer is flashing during the game or something due to the speed of it. So, again, that might be a separate issue for later tho.

**Closed as completed by jessaskey** 2022-05-01 17:37 UTC
Labels: bug
